name: Build and push docker image

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: ${{ github.repository }}
  GHCR: ghcr.io

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub / ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            # DockerHub
            custom-backend
            # GHCR
            docker.io/custom-backend

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: saidfarah
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
